project:
  type: default
  output-dir: docs

render:
  - "content/*.qmd"

format:
  html:
    theme:
      light: cosmo
    css: ../custom.css
    embed-resources: true
    toc: true
    toc-depth: 2
    include-before-body: _extensions/navbar.html
    include-after-body: _extensions/footer.html
